export const GRADE = ['BLOCKER', 'ERROR', 'WARNING', 'UNVERIFIED'] as const;
export const GRADE_WEIGHT = { BLOCKER: 25, ERROR: 10, WARNING: 4, UNVERIFIED: 3 } as const;
// 출시 준비도 = max(0, 100 - Σ(등급별 건수 × 가중치))

export const REASON_CODE = [
  'REST_DAY_CONFLICT', 'OPEN_HOUR_CONFLICT', 'ADMISSION_CUTOFF', 'IN_BREAK_TIME',
  'REST_DAY_UNCERTAIN', 'EVENT_ENDED', 'EVENT_NOT_STARTED', 'TIME_OVERLAP',
  'CONTENT_IMBALANCE', 'MEAL_REST_MISSING', 'MEAL_TIME_SHORT', 'TRAVEL_TIME_SHORT',
  'RAIN_RISK', 'TARGET_MISMATCH', 'PRE_DEPARTURE_CHECK',
] as const; // 15종 — 예외처리 명세 4장과 1:1
